export const CALENDLY_LINK = 'https://calendly.com/rtuerlings/30min'
export const ERROR_LOADING_IMAGE = 'Error loading image'
export const GITHUB_LINK = 'https://github.com/sgnilreutr'
export const LINKEDIN_LINK = 'https://www.linkedin.com/in/robberttuerlings/'
export const TWITTER_LINK = 'https://twitter.com/sgnilreutr'
export const SR_CALENDLY = 'Plan a 30 minute meeting with the author'
export const SR_GITHUB = "A link to the author's GitHub profile"
export const SR_LINKEDIN = "A link to the author's LinkedIn profile"
export const SR_TWITTER = "A link to the author's Twitter profile"
export const LOADING_CONTENT = 'Loading the content'
